version: "3.4"

services:
  neuralwebservice:
    image: neuralwebservice
    container_name: neuralwebservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      AI_API: http://localhost:5003/api
      PORT: 8025
    ports:
      - 8025:8025
    networks:
      ioak-net:
        aliases:
          - neuralwebservice.docker

networks:
  ioak-net:
    external: true
